version: "3.8"
services:
  ascii-art-bot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: []
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
    volumes:
      - ./:/app
    command: npm run dev
