version: "3.8"
services:
  ascii-art-bot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    command: >
      sh -c "npm run deploy-commands &&
             npm run dev"
