name: Trigger auto deployment for ascii-art-bot-testing

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ testing ]
    paths:
    - '**'
    - '.github/workflows/ascii-art-bot-testing-AutoDeployTrigger-de774e52-eba0-4f54-ad6c-4243cf69b82f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ASCIIARTBOTTESTING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ASCIIARTBOTTESTING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ASCIIARTBOTTESTING_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.ASCIIARTBOTTESTING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ASCIIARTBOTTESTING_REGISTRY_PASSWORD }}
          containerAppName: ascii-art-bot-testing
          resourceGroup: discord-bots
          imageToBuild: ghcr.io/ascii-art-bot-testing:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


