---
# .github/workflows/cd.yml
name: CD

on:
  push:
    tags:
      - '*-PR-*'
      - '*-release'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ contains(github.ref_name, '-release') && 'Production' || 'Testing' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/discord-ascii-art-bot:${{ env.github.ref_name }}
          docker build -f Dockerfile -t $IMAGE .
          docker push $IMAGE

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: ${{ contains(github.ref_name, '-release') && 'Production' || 'Testing' }}

    steps:
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: ghcr.io/${{ github.repository_owner }}/discord-ascii-art-bot:${{ env.github.ref_name }}
          resourceGroup: discord-bots
          containerAppName: ascii-art-bot-${{ env.PACKAGE_TAG }}
          containerAppEnvironment: managedEnvironment-discordbots-acc2
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.ACTION_TOKEN }}
          environmentVariables: "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }} DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }} NODE_ENV=${{ github.ref_name }} TERM=xterm-256color COLORTERM=24bit FORCE_COLOR=1"
...
