name: CI/CD

on:
  push:
    branches: [main]

  environment:
    name: Production

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-ref: ghcr.io/${{ github.repository_owner }}/discord-ascii-art-bot:latest

    steps:
      - uses: actions/checkout@v4

      # Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & push
      - name: Build and push Docker image
        run: |
          IMAGE_REF=ghcr.io/${{ github.repository_owner }}/discord-ascii-art-bot:latest
          docker build -f Dockerfile.prod -t $IMAGE_REF .
          docker push $IMAGE_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-to-aci:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances
        run: |
          RESOURCE_GROUP="your-resource-group"
          CONTAINER_NAME="ascii-art-bot"
          IMAGE_REF=ghcr.io/${{ github.repository_owner }}/discord-ascii-art-bot:latest

          # If the container group already exists, delete it first:
          az container delete \
            --resource-group "$RESOURCE_GROUP" \
            --name "$CONTAINER_NAME" \
            --yes || true

          # Create/update container instance
          az container create \
            --resource-group "$RESOURCE_GROUP" \
            --name "$CONTAINER_NAME" \
            --image "$IMAGE_REF" \
            --cpu 1 \
            --memory 1.5 \
            --restart-policy OnFailure \
            --registry-login-server ghcr.io \
            --registry-username "${{ github.actor }}" \
            --registry-password "${{ secrets.GITHUB_TOKEN }}"
