# GH-Actions: .github/workflows/ci-cd.yml
---
name: CI/CD

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
      - testing

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Testing' }}
    env:
      PACKAGE_TAG: ${{ vars.PACKAGE_TAG }}

    outputs:
      image-ref: ghcr.io/${{ github.repository_owner }}/discord-ascii-art-bot:${{ env.PACKAGE_TAG }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/discord-ascii-art-bot:${{ env.PACKAGE_TAG }}
          docker build -f Dockerfile -t $IMAGE .
          docker push $IMAGE
  
  register-commands:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Testing' }}
    env:
      NODE_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'testing' }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Register Slash Commands
        run: npm run deploy-commands


  deploy-to-aca:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Testing' }}
    env:
      # Core Discord bot creds—set in your GitHub Environment secrets
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}

      # Deployment parameters (vars or repo-level)
      NODE_ENV: ${{ vars.NODE_ENV }}
      PACKAGE_TAG: ${{ vars.PACKAGE_TAG }}
      RG: discord-bots
      CA_ENV: discord-bots-aca-env
      CONTAINER_APP_NAME: ${{ vars.CONTAINER_APP_NAME }}
      IMAGE_REF: ${{ needs.build-and-push.outputs.image-ref }}

      # Azure credentials (Environment secret)
      AZURE_CREDENTIALS:   ${{ secrets.AZURE_CREDENTIALS }}

    steps:
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          azureCredentials: ${{ env.AZURE_CREDENTIALS }}
          resourceGroup: ${{ env.RG }}
          containerAppEnvironment: ${{ env.CA_ENV }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          imageToDeploy: ${{ env.IMAGE_REF }}
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GITHUB_TOKEN }}
          ingress: internal
          targetPort: 8080
          environmentVariables: |
            DISCORD_BOT_TOKEN=${{ env.DISCORD_BOT_TOKEN }}
            DISCORD_CLIENT_ID=${{ env.DISCORD_CLIENT_ID }}
            DISCORD_GUILD_ID=${{ env.DISCORD_GUILD_ID }}
            NODE_ENV=${{ env.NODE_ENV }}
...
