# GH-Actions: .github/workflows/ci-cd.yml
---
name: CI/CD

permissions:
  contents: read
  packages: write
  id-token: write

on:
  push:
    branches:
      - main
      - testing

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Testing' }}
    env:
      PACKAGE_TAG: ${{ vars.PACKAGE_TAG }}

    outputs:
      image-ref: ghcr.io/${{ github.repository_owner }}/discord-ascii-art-bot:${{ env.PACKAGE_TAG }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/discord-ascii-art-bot:${{ env.PACKAGE_TAG }}
          docker build -f Dockerfile -t $IMAGE .
          docker push $IMAGE
  
  deploy-to-aca:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Testing' }}
    steps:
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps (v2)
        uses: azure/container-apps-deploy-action@v2
        with:
          # point at your repo + Dockerfile if you wanted to rebuild,
          # but since you already pushed your image above, skip build:
          imageToDeploy: ${{ needs.build-and-push.outputs.image-ref }}
          resourceGroup: discord-bots
          containerAppName: ascii-art-bot-${{ vars.PACKAGE_TAG }}
          containerAppEnvironment: managedEnvironment-discordbots-acc2

          # ensure it knows how to pull from GHCR
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.ACTION_TOKEN }}

          # wire in your bot’s runtime vars
          environmentVariables: " DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }} DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }} NODE_ENV=${{ github.ref_name }} TERM=xterm-256color COLORTERM=24bit FORCE_COLOR=1"
